[versions]
tgbotapi-fsm = "0.12.2"
inmo-tgbotapi = "3.2.0"
koin = "3.2.0"

[libraries]
inmo-tgbotapi = { module = "dev.inmo:tgbotapi", version.ref = "inmo-tgbotapi" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
tgbotapi-fsm = { module = "com.ithersta.tgbotapi:tgbotapi-fsm", version.ref = "tgbotapi-fsm" }
